### ISSUE TITLE
Misuse of `[@@deriving yojson]` on exceptions

### ISSUE THREAD

**Issue by NathanReb** [gborough/safemoney#5]
It seems that in some places in your codebase, you are using `[@@deriving yojson]` on exceptions, e.g. [here](https://github.com/gborough/safemoney/blob/main/lib/discrete.ml#L4).

`ppx_deriving_yojson` does not support deriving de/serializers for exceptions and these fail silently, not actually generating any code.

Staring from the next `ppx_deriving_yojson` version, this won't be a silent error anymore and you will get an error when trying to use `[@@deriving yojson]` on exceptions. We will add an upper bound on the `ppx_deriving_yojson` dependency for older versions of safemoney but you should remove those if you want to be able to use the latest version.

I want to clarify that `[@@deriving sexp]` does work on exceptions, my observation only applies to `ppx_deriving_yojson`.

Sorry for the inconvenience this is causing. It is all due to `ppx_deriving_yojson` being based on `ppx_deriving` rather than directly on `ppxlib`. This won't be a problem anymore going forward.

**Comment by gborough** [comment]
@NathanReb Thank you Nathan for raising this issue, I will get them fixed asap!
